FROM node:20-alpine as build-step

LABEL maintainer="maxime.bourdin.tic@gmail.com"

RUN apk add --no-cache git alpine-sdk bash tzdata

WORKDIR /app

COPY ../package.json ./
COPY ../package-lock.json ./

RUN npm i -g npm
RUN npm install

# COPY . /app

ENTRYPOINT ["npm"]
